# Form implementation generated from reading ui file '/home/dmitriy/Skrivebord/hide-titles/contents/ui/config.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        self.verticalLayout = QtWidgets.QVBoxLayout(Config)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Config)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.primaryOnly = QtWidgets.QCheckBox(parent=Config)
        self.primaryOnly.setObjectName("primaryOnly")
        self.verticalLayout.addWidget(self.primaryOnly)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Config)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Config", "This script will remove the titlebar of maximized windows."))
        self.primaryOnly.setText(_translate("Config", "Only remove titlebar for windows on primary screen"))
